# Generated by Django 3.0.5 on 2021-05-14 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('type', models.CharField(choices=[('B', 'Bar Graph'), ('C', 'Compound Bar Graph'), ('L', 'Line Graph')], default='B', max_length=1)),
                ('yAxis', djongo.models.fields.EmbeddedField(model_container=main.models.Axis)),
                ('xAxis', djongo.models.fields.EmbeddedField(model_container=main.models.Axis)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
