# Generated by Django 3.0.5 on 2021-05-14 10:51

from django.db import migrations
import djongo.models.fields
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210514_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='xAxis',
            field=djongo.models.fields.EmbeddedField(model_container=main.models.Axis, model_form_class=main.models.AxisForm),
        ),
    ]
