# Generated by Django 3.0.5 on 2021-05-14 11:00

from django.db import migrations
import djongo.models.fields
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210514_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='data',
            field=djongo.models.fields.ArrayField(default=None, model_container=main.models.Data),
            preserve_default=False,
        ),
    ]
